language: node_js
node_js:
  - "13.7.0"
services:
  - docker

before_install:
  - docker build -t rozdolsky33/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true rozdolsky33/docker-react-app npm test
os: linux
