language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rozdolsky33/docker-react-app -f Dockerfile.dev .

script:
  - run -e CI=true rozdolsky33/docker-react-app npm run test
